apiVersion: apps/v1
kind: Deployment
metadata:
  name: odd-even-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: odd-even
  template:
    metadata:
      labels:
        app: odd-even
    spec:
      containers:
        - name: odd-even-app
          image: odd-even-app:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          # The portion below is for step 3
          env:
          - name: GREETING_MESSAGE
            valueFrom:
              configMapKeyRef:
                name: odd-even-config
                key: GREETING_MESSAGE