apiVersion: v1
kind: Service
metadata:
  name: odd-even-service
spec:
  selector:
    app: odd-even
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      # nodePort: 30007 # Optional: specify a port otherwise K8s chooses
  # type: ClusterIP # Use this option in step 2
  type: NodePort # Use this option in step 3