services:
  transcription-service:
    build: ./transcription-service
    environment:
      - ASR_MODEL_ID=openai/whisper-large-v3
      - ASR_MODEL_PATH=/models  # Mount point in container
    volumes:
      - ./models:/models  # Map local models to container
      - ./models:/root/.cache/huggingface/hub  # Optional: cache models