version: '3.8'

services:
  granite-speech-asr:
    build: .
    container_name: granite-speech-asr
    ports:
      - "8000:8000"    # API server
      - "8888:8888"    # Jupyter (optional)
    volumes:
      - ./recordings:/granite-speech-asr/recordings
      - ./outputs:/granite-speech-asr/outputs
      - ./models:/granite-speech-asr/models
      - huggingface_cache:/root/.cache/huggingface
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - HF_HOME=/root/.cache/huggingface
      - TRANSFORMERS_CACHE=/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: >
      bash -c "
        python model_download.py &&
        python api_server.py
      "
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  huggingface_cache:
    driver: local