version: '3.8'
services:
  asr-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./audio_files:/app/audio_files
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]