// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserLookup_GetUser_FullMethodName = "/users.UserLookup/GetUser"
)

// UserLookupClient is the client API for UserLookup service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The service definition (like an Interface/Abstract Base Class)
type UserLookupClient interface {
	// A standard unary RPC (one request, one response)
	GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error)
}

type userLookupClient struct {
	cc grpc.ClientConnInterface
}

func NewUserLookupClient(cc grpc.ClientConnInterface) UserLookupClient {
	return &userLookupClient{cc}
}

func (c *userLookupClient) GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, UserLookup_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserLookupServer is the server API for UserLookup service.
// All implementations must embed UnimplementedUserLookupServer
// for forward compatibility.
//
// The service definition (like an Interface/Abstract Base Class)
type UserLookupServer interface {
	// A standard unary RPC (one request, one response)
	GetUser(context.Context, *UserRequest) (*UserResponse, error)
	mustEmbedUnimplementedUserLookupServer()
}

// UnimplementedUserLookupServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserLookupServer struct{}

func (UnimplementedUserLookupServer) GetUser(context.Context, *UserRequest) (*UserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedUserLookupServer) mustEmbedUnimplementedUserLookupServer() {}
func (UnimplementedUserLookupServer) testEmbeddedByValue()                    {}

// UnsafeUserLookupServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserLookupServer will
// result in compilation errors.
type UnsafeUserLookupServer interface {
	mustEmbedUnimplementedUserLookupServer()
}

func RegisterUserLookupServer(s grpc.ServiceRegistrar, srv UserLookupServer) {
	// If the following call panics, it indicates UnimplementedUserLookupServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserLookup_ServiceDesc, srv)
}

func _UserLookup_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserLookupServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserLookup_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserLookupServer).GetUser(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserLookup_ServiceDesc is the grpc.ServiceDesc for UserLookup service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserLookup_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "users.UserLookup",
	HandlerType: (*UserLookupServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _UserLookup_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
