version: '3'

services:
  # CPU Version (for M1 MacBook)
  phi4-cpu:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ${HOME}/.cache/huggingface:/root/.cache/huggingface
    environment:
      - PYTHONUNBUFFERED=1
      - HF_HOME=/root/.cache/huggingface

  # GPU Version (for Linux with 3090Ti)
  phi4-gpu:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ${HOME}/.cache/huggingface:/root/.cache/huggingface
    environment:
      - PYTHONUNBUFFERED=1
      - HF_HOME=/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]