version: "3.8"

services:
  open-webui:
    build: .
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
      - pipelines
    volumes:
      - open-webui:/app/backend/data

  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    ports:
      - "9099:9099"
    volumes:
      - ./pubmed_rag.py:/app/pipelines/pubmed_rag.py
      - ./requirements.txt:/app/requirements.txt
    environment:
      - PIPELINES_REQUIREMENTS_PATH=/app/requirements.txt
      - PIPELINES_ALLOW_LOCAL_INSTALL=true
      - OLLAMA_BASE_URL=http://ollama:11434
      - PYTHONUNBUFFERED=1
      - PUBMED_IP=130.14.29.110
    depends_on:
      - ollama
    dns:
      - 8.8.8.8
      - 1.1.1.1
    extra_hosts:
      - "pubmed.ncbi.nlm.nih.gov:130.14.29.110"

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ~/.ollama/models:/root/.ollama/models
      - ollama_config:/root/.ollama/config
      - ollama_runtime:/root/.ollama/runtime

volumes:
  open-webui:
  ollama_config:
  ollama_runtime: