version: "3.8"

services:
  open-webui:
    build: .
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
      - pipelines
    volumes:
      - open-webui:/app/backend/data

  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    ports:
      - "9099:9099"
    volumes:
      - ./pubmed_rag.py:/app/pipelines/pubmed_rag.py
      - ./requirements.txt:/app/requirements.txt
    environment:
      - PIPELINES_REQUIREMENTS_PATH=/app/requirements.txt
      - PIPELINES_ALLOW_LOCAL_INSTALL=true
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

volumes:
  open-webui:
  ollama: